export type OperatingArea = { areaCode: string; name: string; region: string; coordinates: [number, number]; currency: 'KRW' };
export type Holiday = { countryCode: string; country: string; date: string; name: string; localName: string };
export type ExchangeRate = { countryCode: 'JP' | 'CN' | 'TW' | 'US'; country: string; currencyCode: 'JPY' | 'CNY' | 'TWD' | 'USD'; currencyName: string; unit: number; krwRate: number };
export type ExchangeRateData = { baseCurrency: 'KRW'; updatedAt: string; source: { name: string; url: string }; rates: ExchangeRate[] };
export type DemandPoint = { date: string; demandIndex: number; inboundSearchVolume: number };
export type CountryBookingRate = { countryCode: string; country: string; bookingRateEstimate: number; changePercent: number; searchSharePercent: number; seatCapacity: number; confidence: 'high' | 'medium' | 'low' };
export type MarketRatePoint = { date: string; low: number; median: number; average: number; high: number; sampleSize: number };
export type RoomTypeRate = { roomType: string; currentMedian: number; previousMedian: number; changePercent: number; sampleSize: number };
export type DashboardData = {
  area: OperatingArea;
  generatedAt: string;
  dataMode: 'unavailable' | 'live';
  filters: { radiusKm: number; countryCodes: string };
  summary: { demandIndex: number; demandChangePercent: number; marketMedian: number; marketChangePercent: number; lowRate: number; highRate: number; sampleSize: number } | null;
  inboundDemand: DemandPoint[];
  countryBookingRates: CountryBookingRate[];
  holidays: Holiday[];
  marketRates: MarketRatePoint[];
  roomTypes: RoomTypeRate[];
};
